//
//  StudentLocation.swift
//  OnTheMap
//
//  Created by David Koch on 21.11.22.
//

import Foundation

struct StudentLocation: Codable, Equatable {
    
    //an auto-generated id/key generated by Parse which uniquely identifies a StudentLocation
    let objectId: String
    //an extra (optional) key used to uniquely identify a StudentLocation; should be populated using Udacity account id.
    let uniqueKey: String
    //the first name of the student which matches their Udacity profile first name OR an anonymized name hardcoded in the app
    let firstName: String
    //the last name of the student which matches their Udacity profile last name OR an anonymized name hardcoded in the app
    let lastName: String
    //the location string used for geocoding the student location
    let mapString: String
    //the URL provided by the student
    let mediaURL: String
    //the latitude of the student location (ranges from -90 to 90)
    let latitude: Float
    //the longitude of the student location (ranges from -180 to 180)
    let longitude: Float
    //the date when the student location was created
    let createdAt: String
    //the date when the student location was last updated
    let updatedAt: String
    //the Parse access and control list (ACL), i.e. permissions, for this StudentLocation entry
    //let ACL: AnyObject
    
}

struct StudentLocationResponse: Codable{
    let results: [StudentLocation]
}
